apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uyhr3345s-java-springboot-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/uyhr3345s-java-springboot